### ISSUE TITLE
CORE: Unable to load app ID or API key, falling back to $ionicApp.getApp()

### ISSUE THREAD

**Issue by ty-sang** [driftyco/ionic-service-core#26]
Hi, all,
I'm working on ionic push, and added ionic-service-core. but I get this warning all the time.

Maybe I set the appID and API key at wrong place? 

I did something like this:

```
.config([ '$ionicAppProvider', function($ionicAppProvider) {
  $ionicAppProvider.identify({
    app_id : 'XXXXXX',
    api_key : 'XXXXXXXXXXXXXX'
  });
} ]);
```

also I did in **.io-config.json**

```
{"app_id":"XXXXXX","api_key":"XXXXXXXXXXXXXX"}
```

Any ideas???

**Comment by ericb** [comment]
@shieer Have you run `ionic config build` and `ionic prepare PLATFORM`.

**Comment by ty-sang** [comment]
@ericb  First, Thanks for your reply.

Yes, I did. 
but still get the warning, and i got 
"**onError - errorId: INVALID_SENDER**" on Android build, 

I think maybe the warning cause this Android error.

**Comment by ty-sang** [comment]
@ericb  I found the problem, I install ionic-service-core and ionic-service-push with

```
ionic add ionic-service-core
ionic add ionic-service-push
```

and the default path is lib/ionic-service-core and lib/ionic add ionic-service-push.
but my app structure is not like this, so i moved them and changed the link in index.html

that cause the warning, 

After I move them back to lib/ , warning is removed, and Android error is fixed!

Thanks

**Comment by boyfunky** [comment]
i am still having this issue and hv gone thru all the steps requested.  It works on ios but on android i get the same error. I have done ionic config build, i have made sure it is on my app.js nd its d same on my io-config.json file too 

I do hv one slight distinction, my config.xml widget id is different for my android and my iOS. could tht be the issue?? then is it considered d same app or different app then? This was because for some reasons only apple can knw. It rejected d id used frm android so i had to use another id as my identifier for app store.

**Comment by ericb** [comment]
@boyfunky This library is deprecated in favor of the [ionic-platform-web-client](https://github.com/driftyco/ionic-platform-web-client). You should start fresh with the docs and proceed using that lib.
